In [1]:
import torch
torch.manual_seed(1)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.13.0+cpu


In [2]:
x=torch.empty(5,3)
print(x)

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 1.0928e-38, 9.9184e-39]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247],
        [0.6826, 0.3051, 0.4635]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x=x.new_ones(5,3,dtype=torch.float64)
print(x)

x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.8349, -2.2149,  0.0436],
        [ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571],
        [-0.9013,  0.8138,  0.3871],
        [ 0.5417,  0.6646,  0.3248]])


In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
y=torch.rand(5,3)
print(x+y)

tensor([[-1.1879, -1.8593,  0.4888],
        [ 1.3433,  0.1611,  1.4156],
        [ 0.9029,  2.0137,  1.1579],
        [-0.4247,  0.9800,  1.1916],
        [ 1.1969,  0.8414,  1.1495]])


In [9]:
print(torch.add(x, y))

tensor([[-1.1879, -1.8593,  0.4888],
        [ 1.3433,  0.1611,  1.4156],
        [ 0.9029,  2.0137,  1.1579],
        [-0.4247,  0.9800,  1.1916],
        [ 1.1969,  0.8414,  1.1495]])


In [10]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-1.1879, -1.8593,  0.4888],
        [ 1.3433,  0.1611,  1.4156],
        [ 0.9029,  2.0137,  1.1579],
        [-0.4247,  0.9800,  1.1916],
        [ 1.1969,  0.8414,  1.1495]])


In [11]:
y.add_(x)
print(y)

tensor([[-1.1879, -1.8593,  0.4888],
        [ 1.3433,  0.1611,  1.4156],
        [ 0.9029,  2.0137,  1.1579],
        [-0.4247,  0.9800,  1.1916],
        [ 1.1969,  0.8414,  1.1495]])


In [12]:
print(x)

tensor([[-1.8349, -2.2149,  0.0436],
        [ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571],
        [-0.9013,  0.8138,  0.3871],
        [ 0.5417,  0.6646,  0.3248]])


In [13]:
y=x[0,:]
y+=1
print(y)

tensor([-0.8349, -1.2149,  1.0436])


In [14]:
print(x)

tensor([[-0.8349, -1.2149,  1.0436],
        [ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571],
        [-0.9013,  0.8138,  0.3871],
        [ 0.5417,  0.6646,  0.3248]])


In [15]:
y=x.view(15)
z=x.view(-1,5)
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [16]:
x += 1
print(x)
print(y)

tensor([[ 0.1651, -0.2149,  2.0436],
        [ 2.3240,  0.8995,  1.6443],
        [ 1.5244,  2.0157,  1.2571],
        [ 0.0987,  1.8138,  1.3871],
        [ 1.5417,  1.6646,  1.3248]])
tensor([ 0.1651, -0.2149,  2.0436,  2.3240,  0.8995,  1.6443,  1.5244,  2.0157,
         1.2571,  0.0987,  1.8138,  1.3871,  1.5417,  1.6646,  1.3248])


In [17]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[-0.8349, -1.2149,  1.0436],
        [ 1.3240, -0.1005,  0.6443],
        [ 0.5244,  1.0157,  0.2571],
        [-0.9013,  0.8138,  0.3871],
        [ 0.5417,  0.6646,  0.3248]])
tensor([ 0.1651, -0.2149,  2.0436,  2.3240,  0.8995,  1.6443,  1.5244,  2.0157,
         1.2571,  0.0987,  1.8138,  1.3871,  1.5417,  1.6646,  1.3248])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0996])
0.09960874915122986


In [19]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [20]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [21]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [22]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


In [23]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [25]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [26]:
if torch.cuda.is_available():
    device = torch.device("cuda")          
    y = torch.ones_like(x, device=device)  
    x = x.to(device)                       
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

In [27]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [28]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [29]:
print(x.is_leaf, y.is_leaf)

True False


In [30]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [31]:
a = torch.randn(2, 2) 
a = ((a * 3) / (a - 1))
print(a.requires_grad) 
a.requires_grad_(True)
print(a.requires_grad) 
b = (a * a).sum()
print(b.grad_fn)

False
True


In [32]:
#out.backward()
print(x.grad)

None


In [33]:
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [34]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)


In [35]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)

print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [36]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2 
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2
    
print(x, x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

tensor(1., requires_grad=True) True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [37]:
y3.backward()
print(x.grad)

tensor(2.)


In [38]:
x = torch.ones(1,requires_grad=True)

print(x.data) 
print(x.data.requires_grad) 

y = 2 * x
x.data *= 100 
y.backward()
print(x) 
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])


In [3]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda
import matplotlib.pyplot as plt

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

In [ ]:
import matplotlib.pyplot as plt
labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}
figure = plt.figure(figsize=(8, 8))
cols, rows = 3, 3
for i in range(1, cols * rows + 1):
    sample_idx = torch.randint(len(training_data), size=(1,)).item()
    img, label = training_data[sample_idx]
    figure.add_subplot(rows, cols, i)
    plt.title(labels_map[label])
    plt.axis("off")
    plt.imshow(img.squeeze(), cmap="gray")
plt.show()
